name: chinese_chess_app
description: "Grandmaster Mentor - Ứng dụng huấn luyện Cờ Tướng cao cấp với AI Pikafish."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.5
  device_info_plus: ^12.3.0
  ffi: ^2.1.3
  google_generative_ai: ^0.4.7
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pikafish.nnue
    - assets/app_logo.png
    - assets/puzzles/official_database.pgn
    - assets/sounds/
